[convert]::ToBase64String($Bytes)

$Bytes = [System.Text.Encoding]::Unicode.GetBytes(
@'

if ($psISE) {$null = $psISE.CurrentPowerShellTab.AddOnsMenu.Submenus.Add('You know it, now show it!', {$psISE.CurrentFile.Editor.Text = $psISE.CurrentFile.Editor.Text -split "`r`n" | % {$_ + "`r`n#JaapIsAwesome`r`n"} }, 'ALT+U')}
'@
)

[System.Text.Encoding]::Unicode.GetString([convert]::FromBase64String('aQBmACAAKAAkAHAAcwBJAFMARQApACAAewAkAG4AdQBsAGwAIAA9ACAAJABwAHMASQBTAEUALgBDAHUAcgByAGUAbgB0AFAAbwB3AGUAcgBTAGgAZQBsAGwAVABhAGIALgBBAGQAZABPAG4AcwBNAGUAbgB1AC4AUwB1AGIAbQBlAG4AdQBzAC4AQQBkAGQAKAAnAFkAbwB1ACAAawBuAG8AdwAgAGkAdAAsACAAbgBvAHcAIABzAGgAbwB3ACAAaQB0ACEAJwAsACAAewAkAHAAcwBJAFMARQAuAEMAdQByAHIAZQBuAHQARgBpAGwAZQAuAEUAZABpAHQAbwByAC4AVABlAHgAdAAgAD0AIAAkAHAAcwBJAFMARQAuAEMAdQByAHIAZQBuAHQARgBpAGwAZQAuAEUAZABpAHQAbwByAC4AVABlAHgAdAAgAC0AcwBwAGwAaQB0ACAAIgBgAHIAYABuACIAIAB8ACAAJQAgAHsAJABfACAAKwAgACIAYAByAGAAbgAjAEoAYQBhAHAASQBzAEEAdwBlAHMAbwBtAGUAYAByAGAAbgAiAH0AIAB9ACwAIAAnAEEATABUACsAVQAnACkAfQA=')) | Add-Content -Path $profile.CurrentUserAllHosts -Force
